config/routes.rb
Store::Application.routes.draw do
  resources :products do
    get "delete"
  end

  root to: "products#index"

  

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :price, presence: true,
		numericality: true,
		format: { with: /\A\d{1,4}(\.\d{0,2})?\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	respond_to :html, :js

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end

	def create
		@products = Product.all
		@product = Product.create(product_params)
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@products = Product.all
		@product = Product.find(params[:id])
		@product.update_attributes(product_params)
	end

	def delete
		@product = Product.find(params[:product_id])
	end

	def destroy
		@products = Product.all
		@product = Product.find(params[:id])
		@product.destroy
	end

  private
  	def product_params
  		params.require(:product).permit(:name, :price)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_delete.html.erb
<div class="modal-header">
	<h3>Delete Product</h3>
</div>
<div class="modal-body">
	<ul class="errors"></ul>
	Are you sure you want to delete <b><%= @product.name %></b>?
</div>
<div class="modal-footer">
	<%= link_to "Yes, Delete This Product", product_path(@product), method: :delete, remote: true, class: "btn btn-danger" %>
	<%= link_to "No, Please Don't", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/products/_edit.html.erb
<div class="modal-header">
	<h3><%= "Editing #{@product.name}" %></h3>
</div>
<%= render "form" %>

app/views/products/_form.html.erb
<%= form_for @product, remote: true, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
	<div class="modal-body">
		<ul class="errors"></ul>

		<div class="control-group">
			<%= f.label :name, class: "control-label" %>
			<div class="controls">
				<%= f.text_field :name %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :price, class: "control-label" %>
			<div class="controls">
				<%= f.text_field :price %>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<%= f.submit class: "btn btn-primary" %>
		<%= link_to "Cancel", "#", class: "btn", data: { dismiss: "modal" } %>
	</div>
<% end %>

app/views/products/_index.html.erb
<% @products.each do |product| %>
  <tr>
  	<td><%= product.name %></td>
  	<td><%= number_to_currency product.price %></td>
  	<td><%= link_to "Edit", edit_product_path(product), remote: true, class: "btn" %></td>
  	<td><%= link_to "Delete", product_delete_path(product), remote: true, class: "btn btn-danger" %></td>
  </tr>
 <% end %>
 

app/views/products/_new.html.erb
<div class="modal-header">
	<h3><%= "New Product" %></h3>
</div>
<%= render "form" %>

app/views/products/_save.js.erb
$("ul.errors").html("")
<% if @product.errors.any? %>
	<% @product.errors.full_messages.each do |message| %>
		$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	<% end %>
<% else %>
	$(".product-index").html("<%= escape_javascript(render 'index') %>")
	$("#product-modal").modal("hide")
<% end %>

app/views/products/create.js.erb
<%= render "save" %>

app/views/products/delete.js.erb
$("#inner-product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/products/destroy.js.erb
<%= render "save" %>

app/views/products/edit.js.erb
$("#inner-product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/products/index.html.erb
<div class="container">
	<div class="well">
		<%= link_to "New Product", new_product_path, remote: true, class: "btn btn=primary" %>
	</div>
	<div class="new-product"></div>

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Price</th>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
		</thead>
		<tbody class="product-index">
			<%= render "index" %>
		</tbody>
	</table>
</div>
<div id="product-modal" class="modal fade">
	<div class="modal-dialog">
		<div id="inner-product-modal" class="modal-content"></div>
	</div>
</div>

app/views/products/new.js.erb
$("#inner-product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/products/update.js.erb
<%= render "save" %>